### ISSUE TITLE
npm run test fails when no router is choosen

### ISSUE THREAD

**Issue by Toilal** [Toilal/vue-webpack-template#9]
When no router is chosen, `hooks.ts` is made of comments only, and it seems to break in karma when initializing the test contexts.

```
Error: Module build failed: TypeError: /home/toilal/idea-projects/vue-test/src/hooks.ts: Cannot read property 'indexOf' of undefined
      at Object.relative (/home/toilal/idea-projects/vue-test/node_modules/source-map/lib/util.js:206:15)
      at SourceMapConsumer_generatedPositionFor [as generatedPositionFor] (/home/toilal/idea-projects/vue-test/node_modules/source-map/lib/source-map-consumer.js:731:21)
      at /home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:461:51
      at Array.forEach (native)
      at SourceMapConsumer_eachMapping [as eachMapping] (/home/toilal/idea-projects/vue-test/node_modules/source-map/lib/source-map-consumer.js:155:14)
      at File.mergeSourceMap (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:460:24)
      at File.generate (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:719:25)
      at File.transform (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:554:17)
      at /home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/pipeline.js:50:19
      at File.wrap (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:564:16)
      at Pipeline.transform (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
      at transpile (/home/toilal/idea-projects/vue-test/node_modules/babel-loader/lib/index.js:46:20)
      at Object.module.exports (/home/toilal/idea-projects/vue-test/node_modules/babel-loader/lib/index.js:163:20)
  at index.ts:12142
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: Module build failed: TypeError: /home/toilal/idea-projects/vue-test/src/hooks.ts: Cannot read property 'indexOf' of undefined
      at Object.relative (/home/toilal/idea-projects/vue-test/node_modules/source-map/lib/util.js:206:15)
      at SourceMapConsumer_generatedPositionFor [as generatedPositionFor] (/home/toilal/idea-projects/vue-test/node_modules/source-map/lib/source-map-consumer.js:731:21)
      at /home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:461:51
      at Array.forEach (native)
      at SourceMapConsumer_eachMapping [as eachMapping] (/home/toilal/idea-projects/vue-test/node_modules/source-map/lib/source-map-consumer.js:155:14)
      at File.mergeSourceMap (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:460:24)
      at File.generate (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:719:25)
      at File.transform (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:554:17)
      at /home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/pipeline.js:50:19
      at File.wrap (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:564:16)
      at Pipeline.transform (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
      at transpile (/home/toilal/idea-projects/vue-test/node_modules/babel-loader/lib/index.js:46:20)
      at Object.module.exports (/home/toilal/idea-projects/vue-test/node_modules/babel-loader/lib/index.js:163:20)
  at index.ts:12142
```

Adding a dummy statement in `hooks.ts` fix the issue.

**Comment by Toilal** [comment]
I've found an issue in babel-loader (https://github.com/babel/babel-loader/issues/188), and also found a workaround.
